<?php
/*************************************
PLEASE DO NOT EDIT THIS FILE, MAKE 
YOUR CHANGES IN CONFIG.PHP - THIS FILE 
IS BEEING CHANGED BY UPDATES OFTEN
*************************************/
/*******************
GENERAL SERVERCONFIG
*******************/
$cqrweblog_root="/";  // webserver root for cqrweblog, relative to your webroot, for http://server:port/path its just /path

/*******************
GENERAL LOG SETTINGS
*******************/
$defaultlog="1";           // this is the default log (override: log_id=N)
$defaultcount="50";        // count of qsos to show per default in the tables
$max_public_count="50";    // max count of qsos to show on the public pages
$publog_enabled=true;      // enable public log, true or false
$pubsearch_enabled=true;   // if publog is enabled, enable/disable logsearch for visitors
$debugmode=false;          // debug-mode
$exportdir="tmp/";         // where to export the adi files? has to be readable/writable by the webserver
$hamqth_api = true;        // enable/disable hamqth-api (switches to local dxcc resolution and disables cluster, if false)
													 // if your cqrweblog instance is very slow, consider turning $hamqt_api to false, hamqth.com might have problems!
$cluster_spot_num =50;

/**************
DEFAULT REPORTS
**************/
$defaultmode="CW";
$default_cw_rapport="599";
$default_ssb_rapport="59";

/***************************************************
INDIVIDUAL LOG SETTINGS, ARRAY INDEX REFLECTS LOG ID
array(offset, log1setting, log2setting, log3setting)
***************************************************/

$altstats = array ( "offset", false, false, false, true, false);        // let the user decide, whether to use stats or stats2 dxcc-presentation
$enable_cluster = array ( "offset", false, false, false, true, false);  // let the user decide, if the cluster is enabled:
$enable_help = array ( "offset", false, false, false, true, false);     // show help for users:
$enable_searchcount = array ( "0", false, false, false, true, true);		// let the user decide, if searches are counted. To use this, searches.txt has 
																																				// to exist and has to be writable by the webserver (in most setups chmod 775 should work)

/*************
CLUSTER COLORS
*************/
$atnocolor = "red";
$newbandcolor ="deeppink";
$newmodecolor = "green";
$confirmedcolor ="black";
$workedcolor="blue";
$dupecolor="grey";
?>
